### ISSUE TITLE
Windows ver can't locate tsschecker

### ISSUE THREAD

**Issue by xapenny** [SpiderCab/AutoTSS#2]
like this 

![1](https://user-images.githubusercontent.com/25687345/41033849-7076b672-69ba-11e8-90a2-612da07e21ae.png)

**Comment by jlapplications** [comment]
Added the same issue yesterday haha

**Comment by jlapplications** [comment]
Also if you want to move the folder location add these to make it portable

Example for auto:

@ECHO OFF
TITLE "AutoTSS - AutoMode"
set mypath=%cd%
:AutoMode
python "%mypath%\autotss.py"
timeout /t 30
goto AutoMode

**Comment by SpiderCab** [comment]
Will fix today when I have time
